### ISSUE TITLE
the whole /100 /10000 nonsense??

### ISSUE THREAD

**Issue by Axilotl17** [Scraft161/energy-enumerated#2]
Why does adding 1 energy add .01 and adding 1 light add .0001
This is so dumb just use decimals...

I had a stroke trying to understand why you did this and fucking died
I started to fix it but realized that you might not want me too

**Comment by Axilotl17** [comment]
id like to point out #1 is caused by this, and im pretty sure antimatter-matter annihilation is meant to give 10 and not .1 energy....

**Comment by Scraft161** [comment]
I would love to use decimals, but due to how floating points work I cannot use them reliably without drift.

numbers in javascript are already weird enough and I want to avoid anything that will interfere with gameplay too much.

if you have a viable alternative that does not cause drift or relies on exponent tricks (like the break-infinity library) then do tell me.

(leaving this open for a bit more discussion)

**Comment by Axilotl17** [comment]
how does it cause drift?

**Comment by Scraft161** [comment]
the way floating points are defined by IEEE leans that they will only be precise until a certain point.
adding `0.1` and `0.2` together in the JavaScript console for example will result in `0.30000000000000004`.

not a big deal as we can ignore anything below the hundreds place here; but pruning this would be another floating point operation I didn't want to deal with and leaving it would cause this drift to worsen.

since I knew I wasn't going to go below the hundreds place for this game on many values it seemed logical to keep everything as integer math and only do the conversion to floating point when displaying (in reality we could also skip this if we made our own formatter to place the dot and space things out; but I'm lazy and this is adequate for the time being).

another thing with JS numbers is that floating points here can have extra weirdness if not handled correctly and it just seemed easier to me to sidestep this issue entirely by keeping all the backend numbers as integers.

this is a fine approach as long as it is handled correctly and not by a dumbass like me, but whether you think this is a good idea or not is your opinion, fact of the matter is that this is the solution I think works best for this scenario even if it may cause input in the console to be weird and opens the door to bugs like these.

again, I'm open to any other suggestions you (or other people stumbling across this) may have as I will admit that this solution is far from perfect.

**Comment by Axilotl17** [comment]
round to nearest 1000th?? you arent going more specific then that anyways...
